### ISSUE TITLE
Compiling for Python 3.9

### ISSUE THREAD

**Issue by mexicantexan** [bweigel/aws-lambda-tesseract-layer#155]
How would I do this? 

For context, I have a lambda function that runs on Python3.9 and needs to use Tesseract so I was going to build it following your instructions and then link the layer. Would I even need to build this in Python 3.9, or would Python3.8 be fine since it is a separate layer?

My bad, not really an issue, more of just a general question.

**Comment by bweigel** [comment]
Hello @mexicantexan,

sorry for the longish delay. Your issue must have slipped somehow.

You can [pack the binaries directly into a layer](https://github.com/bweigel/aws-lambda-tesseract-layer#ready-to-use-binaries) and use this directly with your Lambda function. No matter if Python 3.8, 3.9, 3.10 or other runtime. All runtimes that use Amazon-Linux 2 should be compatible (although I have not explicitly tested all).

Cheers
