### ISSUE TITLE
Recent releases missing layer zip

### ISSUE THREAD

**Issue by aldenquimby** [bweigel/aws-lambda-tesseract-layer#243]
Hello hello!

The two most recent releases are missing the layer zip:

<img width="880" alt="image" src="https://github.com/bweigel/aws-lambda-tesseract-layer/assets/2145098/9e355e2d-0ef1-4de2-8283-10414fac01d8">

Is this something you could add, or would you recommend using one of the other install/setup methods instead now?

Thank you

**Comment by bweigel** [comment]
Hey @aldenquimby. Thanks for pointing this out. I've fixed it for all the releases but 5.3.4, because the artifact from the GitHub action was missing. I have also fixed the release workflow and hopefully this will not be an issue any further.
