### ISSUE TITLE
Error opening data file

### ISSUE THREAD

**Issue by Stijn-Depla** [bweigel/aws-lambda-tesseract-layer#7]
Hi Benjamin,

Thanks very much for detailing out how to set up tesseract as a lambda layer. It has been super helpful to me. 

Although I recognize this directory is probably not actively maintained anymore, I thought I'd report a bug to help others avoid running into it as well. 

The locations from which the DockerFile (https://github.com/bweigel/aws-lambda-tesseract-layer/blob/master/Dockerfile) downloads the tessdata files seem to be outdated. This causes a slightly misleading error (in pytesseract):

'Error opening data file Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.

The problem is not the location of the tessdata directory, but its contents which are downloaded from stale links. I managed to get things working by updating: 
curl -L https://github.com/tesseract-ocr/tessdata${TESSERACT_DATA_SUFFIX}/raw/${TESSERACT_DATA_VERSION}/osd.traineddata > osd.traineddata && \

to:
curl -L https://github.com/tesseract-ocr/tessdata${TESSERACT_DATA_SUFFIX}/raw/master/osd.traineddata > osd.traineddata && \

**Comment by bweigel** [comment]
Should all be fixed.
